// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: SecondaryFirebaseOptions.currentPlatform,
/// );
/// ```
class SecondaryFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'SecondaryFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'SecondaryFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'SecondaryFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWjeIjGY_9B1m6JhT7Tkt2AtvRtiW8mk',
    appId: '1:1024532317222:web:44dbb556f20fe998e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    authDomain: 'ondamenu-pos.firebaseapp.com',
    storageBucket: 'ondamenu-pos.appspot.com',
    measurementId: 'G-L2XVZWQYST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWjeIjGY_9B1m6JhT7Tkt2AtvRtiW8mk',
    appId: '1:1024532317222:web:44dbb556f20fe998e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    storageBucket: 'ondamenu-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWjeIjGY_9B1m6JhT7Tkt2AtvRtiW8mk',
    appId: '1:1024532317222:ios:44dbb556f20fe998e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    storageBucket: 'ondamenu-pos.appspot.com',
    iosBundleId: 'com.example.odmUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQWjeIjGY_9B1m6JhT7Tkt2AtvRtiW8mk',
    appId: '1:1024532317222:ios:44dbb556f20fe998e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    storageBucket: 'ondamenu-pos.appspot.com',
    iosBundleId: 'com.example.odmUi.RunnerTests',
  );
}
